### PR TITLE
sync develop branch with team-vigir

### PR DESCRIPTION
**Pull request by benmaidel**

### CODE REVIEW

**Comment by fmessmer** [comment]
@benmaidel @LoyVanBeek 
then let's wait a few days....maybe https://github.com/team-vigir/flexbe_behavior_engine/pull/132 gets merged soon....then it will be included in the sync....

**Comment by LoyVanBeek** [comment]
I don't think it'll get tmerged soon. I also ran into an issue with FlexBE's develop branch, so I undid my earlier rebase: https://github.com/team-vigir/flexbe_behavior_engine/pull/132#issuecomment-720411834

**Comment by fmessmer** [comment]
apparently, there is an issue with syncing with `develop` branch -> see https://github.com/team-vigir/flexbe_behavior_engine/pull/132#issuecomment-720411834

@benmaidel which branch/version/hash do you use for Kevin development?

**Comment by benmaidel** [comment]
I use https://github.com/mojin-robotics/flexbe_behavior_engine/tree/develop. No problems so far

**Comment by fmessmer** [comment]
- @LoyVanBeek's PR has been merged, so the `require_launch_success` feature is included in this PR 
- https://github.com/mojin-robotics/mbl/pull/168 shows that the sync does not break anything (obvious) in `mbl`
- https://github.com/mojin-robotics/mojin_atf/pull/31 cannot be used to verify this for `moin_atf_mbl` due to some `tf_metric` issue in `atf`

@benmaidel will test the `team-vigir/flexbe_behavio_engine#develop` branches together with the `mojn_flexbe` PRs and with `kevin` emulation....if he is happy we will merge this PR

**Comment by fmessmer** [comment]
at least https://github.com/mojin-robotics/mojin_flexbe/pull/72 (probaly other states/behaviors) do not work (or their tests pass) with this update PR....
thus, we'll have to investigate the consequences of this sync a bit more...and keep `mojin-robotics/flexbe_behavior_engine#develop` at the current state until then...

**Comment by benmaidel** [comment]
I've tested https://github.com/FlexBE/flexbe_app/tree/develop and https://github.com/team-vigir/flexbe_behavior_engine/tree/develop against the kevin emulation. These versions do not seem to fit to each other. The FlexBE app shows the wrong transition although the execution engine is proposing the right one. E.g. A State has two transitions `succeeded` and `failed`. Pressing on the `succeeded` transition will result in an `failed` outcome.
Could produce this error only on our custom states that use the usedata_or_member feature. Seems like the numerical order of the transitions changed and our custom changes to the flexbe_app do not fit to that. Need to further investigate the root of the problem.

**Comment by LoyVanBeek** [comment]
I think I've also observed this issue once of twice with Robotise. Had some other issues with userdata then too IIRC, so I did not look into this further. But I don't think it has anything to do with the `userdata_or_member` stuff, since AFAIK we don't use that for Robotise.

**Comment by LoyVanBeek** [comment]
FYI: I'm currently running `flexbe_behavior_engine` on version `1.3.1` and `flexbe_app` on version [`mojin-devel@d2480083d28b92c6a6e7b3e668ba9e8f83edcff6`](https://github.com/mojin-robotics/flexbe_app/commit/d2480083d28b92c6a6e7b3e668ba9e8f83edcff6)

**Comment by benmaidel** [comment]
> FYI: I'm currently running `flexbe_behavior_engine` on version `1.3.1` and `flexbe_app` on version [`mojin-devel@d2480083d28b92c6a6e7b3e668ba9e8f83edcff6`](https://github.com/mojin-robotics/flexbe_app/commit/d2480083d28b92c6a6e7b3e668ba9e8f83edcff6)

This combination works for me too. Or at least with the BMW Behavior. Needs to be checked against the other behaviors so the error I've described here https://github.com/mojin-robotics/flexbe_behavior_engine/pull/6#issuecomment-732954411 is not happening anymore.

**Comment by fmessmer** [comment]
here is the current branch combination - which I used for kinetic/noetic compatibility:

kinetic:
```
- git:
    local-name: flexbe_app
    uri: git@github.com:mojin-robotics/flexbe_app
    version: mojin-devel
- git:
    local-name: flexbe_behavior_engine
    uri: git@github.com:mojin-robotics/flexbe_behavior_engine
    version: develop
- git:
    local-name: generic_flexbe_states
    uri: git@github.com:mojin-robotics/generic_flexbe_states
    version: master
- git:
    local-name: mojin_flexbe
    uri: git@github.com:mojin-robotics/mojin_flexbe
    version: kinetic-devel
```

noetic:
```
- git:
    local-name: flexbe_app
    uri: git@github.com:mojin-robotics/flexbe_app
    version: mojin-devel
#- git: # use released version
#    local-name: flexbe_behavior_engine
#    uri: git@github.com:mojin-robotics/flexbe_behavior_engine
#    version: develop
- git:
    local-name: generic_flexbe_states
    uri: git@github.com:mojin-robotics/generic_flexbe_states
    version: master
- git:
    local-name: mojin_flexbe
    uri: git@github.com:mojin-robotics/mojin_flexbe
    version: kinetic-devel
```

**Comment by fmessmer** [comment]
as discussed:
@benmaidel will do some testing with https://github.com/mojin-robotics/flexbe_behavior_engine/pull/6 and https://github.com/mojin-robotics/flexbe_app/pull/10 in order to get this merged

**Comment by fmessmer** [comment]
branch successfully tested in:
- https://github.com/mojin-robotics/mojin_flexbe/pull/88
- https://github.com/mojin-robotics/mbl/pull/172
- https://github.com/mojin-robotics/kevin_statemachine/pull/7

**Review by fmessmer — APPROVED** [review]

**Pull request merged**
