### PR TITLE
ensure all concurrent container states get executed

### PR DESCRIPTION
**Pull request by benmaidel**
This is just a quick fix for the problem described here: https://github.com/team-vigir/flexbe_behavior_engine/issues/87

### CODE REVIEW

**Comment by LoyVanBeek** [comment]
Works like a charm in FlexBE :heart: 

Travis misses `xvfb-run` which on my box can be installed with `xvfb`. 
That's a virtual x frame buffer to render the GUI to in travis I think:
https://github.com/FlexBE/flexbe_ci/blob/master/ci_scripts/script.bash#L19

**Comment by LoyVanBeek** [comment]
> Can we fix travis?

https://github.com/FlexBE/flexbe_ci/pull/1

**Comment by fmessmer** [comment]
lets see whether https://github.com/mojin-robotics/flexbe_behavior_engine/pull/2 succeeds...then we can rebase this PR and merge as @LoyVanBeek already approved the feature/fix proposed in this PR...

**Comment by fmessmer** [comment]
just saw https://github.com/team-vigir/flexbe_behavior_engine/pull/88
as an upstream fix...should we use https://github.com/team-vigir/flexbe_behavior_engine/tree/fix/concurrency_sleep instead?

**Comment by benmaidel** [comment]
As this is intended to just be a quick fix for us. This PR is not needed anymore.

**Pull request closed without merging**
