### PR TITLE
 sync develop branch with team-vigir + lvb require_launch_success

### PR DESCRIPTION
**Pull request by fmessmer**
@benmaidel 
@LoyVanBeek 
would it make sense to sync our flexbe overlays with upstream?

### CODE REVIEW

**Comment by LoyVanBeek** [comment]
@benmaidel I don't recall the reasons for forking it, besides pinning it for stability.
Our fork is not ahead (anymore) so if we can edit/test/run our behaviors and states, we should be fine I think.

**Comment by benmaidel** [comment]
As you suspected, we've just forked this repo to mojin to be able to pin point it to a certain version.

**Comment by benmaidel** [comment]
I'd use https://github.com/team-vigir/flexbe_behavior_engine/tree/master as the base branch for the sync. @LoyVanBeek PR https://github.com/team-vigir/flexbe_behavior_engine/pull/132 is not merged by now.
@LoyVanBeek are you sure your PR should point to the `master` branch? They do normally go to the `develop` branch of flexbe

**Comment by LoyVanBeek** [comment]
Updated https://github.com/team-vigir/flexbe_behavior_engine/pull/132 to target `develop`

**Comment by fmessmer** [comment]
@benmaidel @LoyVanBeek 
then let's wait a few days....maybe https://github.com/team-vigir/flexbe_behavior_engine/pull/132 gets merged soon....then it will be included in the sync....

**Comment by benmaidel** [comment]
@fmessmer you could already change the PR to `team-vigir:master`?

**Comment by fmessmer** [comment]
@LoyVanBeek 
your feature branch is behind `team-vigir/flexbe_behavior_engine#develop`
if you update your feature branch than this PR #5 is the same as #6 - just including https://github.com/team-vigir/flexbe_behavior_engine/pull/132 in addition

**Comment by LoyVanBeek** [comment]
Agh, of course. I rebased my feature branch in https://github.com/team-vigir/flexbe_behavior_engine/pull/132

**Comment by fmessmer** [comment]
apparently, there is an issue with syncing with `develop` branch -> see https://github.com/team-vigir/flexbe_behavior_engine/pull/132#issuecomment-720411834
so this PR is syncing `master` + https://github.com/team-vigir/flexbe_behavior_engine/pull/132

**Comment by LoyVanBeek** [comment]
I'm running this locally and that works fine. Someone other than me should verify

**Comment by fmessmer** [comment]
@LoyVanBeek's PR has been merged and is not part of #6

**Pull request closed without merging**
