### PR TITLE
get userdata by service

### PR DESCRIPTION
**Pull request by HannesBachter**
fixes https://github.com/4am-robotics/orga/issues/3602
adds `/flexbe/get_userdata` service that returns the specified userdata (and prints it to the terminal):

```
$ rosservice call /flexbe/get_userdata "userdata_key: 'nav_goal'" 
success: True
message: "Found 2 occurences of 'nav_goal'"
userdata: 
  - 
    state: "BmwIdle/MoveToStart/"
    key: "nav_goal"
    type: "list"
    data: "['corridor_end', 'corridor_start', 'corridor_start']"
  - 
    state: "BmwIdle/MoveToStart/MoveBaseStartpoint/"
    key: "nav_goal"
    type: "list"
    data: "['corridor_start']"

$ rosservice call /flexbe/get_userdata "userdata_key: ''" 
success: True
message: "Found 20 occurences of ''"
userdata: 
  - 
    state: "BmwIdle/PrepareRobot/"
    key: "num_internal_storages_used"
    type: "int"
    data: "1"
  - 
    state: "BmwIdle/PrepareRobot/"
    key: "internal_storages_used"
    type: "dict"
    data: "{'9466022-05_a3464f3d-7c4b-4996-88d6-e28328752343': 'internal_shelf_0'}"
  - 
    state: "BmwIdle/PrepareRobot/"
    key: "object_ids"
    type: "NoneType"
    data: "None"
  - 
    state: "BmwIdle/PrepareRobot/PrepareRobotToNavigate/"
    key: "prepare_robot_step_list"
    type: "list"
    data: "[{'component': 'gripper', 'parameter': 'bmw_home', 'mode': 'pkp'}, {'component':\
  \ 'arm', 'parameter': 'transport', 'mode': 'pkp'}]"
  - 
    state: "BmwIdle/PrepareRobot/PrepareRobotToNavigate/"
    key: "prepare_robot_step_index"
    type: "int"
    data: "1"
  - 
    state: "BmwIdle/PrepareRobot/PrepareRobotToNavigate/"
    key: "prepare_robot_step_next"
    type: "dict"
    data: "{'component': 'gripper', 'parameter': 'bmw_home', 'mode': 'pkp'}"
  - 
    state: "BmwIdle/PrepareRobot/PrepareRobotToNavigate/"
    key: "prepare_robot_step_component"
    type: "str"
    data: "gripper"

...
```

### CODE REVIEW

**Comment by HannesBachter** [comment]
Unfortunately I cannot reproduce the rostest failure
```
  [ROSTEST]-----------------------------------------------------------------------
  
  [flexbe_core.rosunit-test_flexbe_core/test_concurrency_container][FAILURE]------
  0.000387287 != 0.1 within 2 places (0.099612713 difference)
    File "/usr/lib/python3.8/unittest/case.py", line 60, in testPartExecutor
      yield
    File "/usr/lib/python3.8/unittest/case.py", line 676, in run
      self._callTestMethod(testMethod)
    File "/usr/lib/python3.8/unittest/case.py", line 633, in _callTestMethod
      method()
    File "/root/target_ws/src/flexbe_behavior_engine/flexbe_core/test/test_core.py", line 361, in test_concurrency_container
      self.assertAlmostEqual(cc.sleep_duration, .1, places=2)
    File "/usr/lib/python3.8/unittest/case.py", line 966, in assertAlmostEqual
      raise self.failureException(msg)
  --------------------------------------------------------------------------------
  
  [flexbe_core.rosunit-test_flexbe_core/test_cross_combinations][passed]
  [flexbe_core.rosunit-test_flexbe_core/test_event_state][passed]
  [flexbe_core.rosunit-test_flexbe_core/test_lockable_state][passed]
  [flexbe_core.rosunit-test_flexbe_core/test_manually_transitionable_state][passed]
  [flexbe_core.rosunit-test_flexbe_core/test_operatable_state][passed]
  [flexbe_core.rosunit-test_flexbe_core/test_preemptable_state][passed]
  [flexbe_core.rosunit-test_flexbe_core/test_ros_state][passed]
  [flexbe_core.rosunit-test_flexbe_core/test_user_data][passed]
  
  SUMMARY
   * RESULT: FAIL
   * TESTS: 9
   * ERRORS: 0
   * FAILURES: 1
```
on my machine.
I also cannot understand where this failure comes from, because I neither changed something in the `test_core.py` nor in the `ConcurrencyContainer` (nor in it's parents)

The `test_concurrency_container` is executed here: https://github.com/mojin-robotics/flexbe_behavior_engine/blob/develop/flexbe_core/test/test_core.py#L330 and checks for the `sleep_duration` from here: https://github.com/mojin-robotics/flexbe_behavior_engine/blob/develop/flexbe_core/src/flexbe_core/core/concurrency_container.py#L24 which takes the least remaining time until the state is run again from here: https://github.com/mojin-robotics/flexbe_behavior_engine/blob/develop/flexbe_core/src/flexbe_core/core/ros_state.py#L24
But neither of those pieces of code have been changed recently and I realised that when I add some print statements, the `sleep_duration` actually gets closer to the desired value...

**Comment by LoyVanBeek** [comment]
Tests pass locally here too

**Comment by LoyVanBeek** [comment]
Regardless, this is very weird. This PR only makes changes to `flexbe_onboard` but makes `flexbe_core` fail. There's no dependency of `core` to `onboard` too. 

My only conclusion is that this test is simply flaky, although it has been passing since forever. The effect that the prints have that @HannesBachter mention also do point to some timing issue.

**Comment by LoyVanBeek** [comment]
On my own version of this PR (https://github.com/mojin-robotics/flexbe_behavior_engine/pull/29), I'll try each if each separate commit makes it through CI, kinda like git bisect, to find the offending commit. 

- Even resetting the branch back to be at `develop` fails the offending test. So the changes are not due to any of Hannes's changes (as expected) but the test is simply unstable. And that is what I'd expect reading the code behind it. Such timing is not something that is ever easy to test. 
I suggest simply commenting the test or asserts that check the timing in `ConcurrencyContainer`

**Comment by fmessmer** [comment]
I still would like to understand the issue with the timing in the test because in #22 that test passed reliably
I also triggered another `CI` job on the default branch - and that also passes

The failing test must have something to do with the addition in this PR
(maybe the additional `import` make something take longer or something)

**Review by fmessmer — APPROVED** [review]

**Pull request merged**
