### PR TITLE
make usable with install space

### PR DESCRIPTION
**Pull request by HannesBachter**
when package is in install space, take `.py` files from python module install space

worked like this on `cob-stud-9`

### CODE REVIEW

**Review by fmessmer — CHANGES_REQUESTED** [review]
this should be proposed to `team-vigir` with reference to https://github.com/team-vigir/flexbe_behavior_engine/issues/104

**Comment by HannesBachter** [comment]
is also proposed here: https://github.com/team-vigir/flexbe_behavior_engine/pull/106

**Comment by fmessmer** [comment]
@HannesBachter 
please put some pressure on https://github.com/team-vigir/flexbe_behavior_engine/pull/104 and https://github.com/team-vigir/flexbe_behavior_engine/pull/106, I'd rather have feedback from the flexbe maintainer and sync from the main repo than merging something in our fork...

we'd also need an answer for behaviors to be executable vs. python modules
@benmaidel @LoyVanBeek FYI

**Comment by fmessmer** [comment]
behaviors are modules according to https://github.com/team-vigir/flexbe_behavior_engine/issues/104#issuecomment-582534461

@HannesBachter is currently testing https://github.com/team-vigir/flexbe_behavior_engine/pull/110 - instead of this PR

**Comment by fmessmer** [comment]
https://github.com/team-vigir/flexbe_behavior_engine/pull/110 is merged
thus, this PR is not needed anymore

@HannesBachter 
I already updated `mojin-robotics/develop` branch to include the install space fix...you can use that branch in https://github.com/mojin-robotics/mojin_atf/pull/3

**Pull request closed without merging**
